# SPDX-License-Identifier: MIT
# Copyright (C) 2021 Roland Csaszar
#
# Project:  TestHaskell
# File:     linux_test.yml
# Date:     16.May.2021
###############################################################################
name: Tests Ubuntu 20.04

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Packages"]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests-coverage:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Stack install
        uses: actions/cache@v2
        with:
          path: ~/.stack/
          key: ${{ runner.os }}-Stack-Cache-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-Stack-Cache

      - name: Setup Tools
        run: |
          stack install

      - name: Run Tests & Coverage
        run: |
          cd $GITHUB_WORKSPACE
          stack clean
          stack test --coverage  || true
          TIX=$(stack path --local-hpc-root)/TestHaskell/TestHaskell-test/TestHaskell-test.tix
          MIX=$(stack path --dist-dir)/hpc
          stack exec -- hpc-codecov --verbose -o coverage.json -m "${MIX}" "${TIX}"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          files: ./coverage.json
          directory: ./coverage/reports/
          # flags: unittest
          env_vars: OS,PYTHON
          name: Linux-Test-Src
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Coverage Report
          path: ./coverage.json

  tests:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Tools
        run: |
          stack install

      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE
          stack clean
          stack test
      # - uses: actions/upload-artifact@v2
      #   if: ${{ always() }}
      #   with:
      #     name: Test Results
      #     path: ./test_results/*.xml
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: ./test_results/jresult.xml
